FROM node:20-alpine
RUN npm install -g pnpm

WORKDIR /app

# 루트 및 database 관련 의존성만 복사
COPY pnpm-lock.yaml pnpm-workspace.yaml package.json ./
COPY packages/database ./packages/database
COPY package.json ./package.json
COPY tsconfig.base.json ./tsconfig.base.json
COPY tsconfig.json ./tsconfig.json

RUN pnpm install
