# apps의 api 폴더 빌드 및 배포
name: backend build and deploy
on:
  push:
    paths:
      - "apps/api/**"
    branches:
      - main
  pull_request:
    paths:
      - "apps/api/**"
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted # 직접 띄운 도커 러너를 사용함

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy with Docker Compose
        env:
          # git actions의 환경변수 입력가능
          PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
        run: |
          docker network inspect $NETWORK_NAME >/dev/null 2>&1 || \
          docker network create $NETWORK_NAME

          docker-compose -f ci/docker-composes/docker-compose.prod.yaml up -d --build api
