# apps의 web 폴더 빌드 및 배포
name: web build and deploy
on:
  push:
    paths:
      - "apps/web/**"
    branches:
      - main
  pull_request:
    paths:
      - "apps/web/**"
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted # 직접 띄운 도커 러너를 사용함

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy with Docker Compose
        env:
          # git actions의 환경변수 입력가능
          PROJECT_NAME: ${{ secrets.PROJECT_NAME }}

        run: |
          echo "디버그 - API URL: $API_BASE_URL"
          echo "디버그 - NEXT_PUBLIC_API_BASE_URL: $NEXT_PUBLIC_API_BASE_URL"
          echo "디버그 - KAKAO_REST_API_KEY: $KAKAO_REST_API_KEY"
          echo "디버그 - KAKAO_REDIRECT_URI: $KAKAO_REDIRECT_URI"

          docker network inspect $NETWORK_NAME >/dev/null 2>&1 || \
          docker network create $NETWORK_NAME

          docker-compose -f ci/docker-composes/docker-compose.prod.yaml build --no-cache web

          docker-compose -f ci/docker-composes/docker-compose.prod.yaml up -d web
